logstash:
  extends:
    file: common.yml
    service: logstash
  links:
  - elastic

mongodb:
  extends:
    file: common.yml
    service: mongodb

redis:
  extends:
    file: common.yml
    service: redis

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic
  ports:
  - "5601:5601"
  image: sourcefabric/kibana:liveblogmaster

elastic:
  extends:
    file: common.yml
    service: elastic

postfix:
  extends:
    file: common.yml
    service: postfix

fakes3:
  extends:
    file: common.yml
    service: fakes3

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
   - fakes3
  ports:
   - "443:443"
   - "80:80"
